### PR TITLE
[manager] verify program type for tail_call map

### PR DESCRIPTION
**Pull request by nplanel**
### What does this PR do?

Tail call map must have an unique program type per program array (post check)

### Motivation

Inserting multiple program (fd) type in a prog array is possible, but will not work

### CODE REVIEW

**Comment by brycekahle** [comment]
How would this fail without this code? Would the verifier reject the program? or would the map put fail?

**Comment by brycekahle** [comment]
@nplanel mind answering my earlier question? What happens if two different program types share the same prog array map? Is that even allowed?

**Comment by nplanel** [comment]
@brycekahle sorry I didn't see your last messages, I don't remember the full context but hit this issue and had a chat with @Gui774ume

**Comment by nplanel** [comment]
@brycekahle it's when you mix socket filter type and trancepoint or uprobes ....
When the caller setup the tail calls via manager.TailCallRoute

**Comment by brycekahle** [comment]
closing for now. If we decide we need/want this, we can open a new PR.

**Pull request closed without merging**
