### PR TITLE
[Manager] Add KeepKernelBTF option

### PR DESCRIPTION
**Pull request by Gui774ume**
### What does this PR do?

This PR adds an option to keep the Kernel types so that CloneProgram can still work. This PR doesn't change the current default state of the manager.

### Motivation

Fix CloneProgram usage with BTF.

### CODE REVIEW

**Comment by brycekahle** [comment]
While this would work, I think it might better if we could scope an additional kernel BTF load/release around the `CloneProgram` call. That way you don't have to opt-in to a permanent memory increase to use `CloneProgram`.

**Comment by Gui774ume** [comment]
> While this would work, I think it might better if we could scope an additional kernel BTF load/release around the `CloneProgram` call. That way you don't have to opt-in to a permanent memory increase to use `CloneProgram`.

Is it OK with you if I do it in another PR ? This will be a breaking change for the Datadog Agent (= will take more time to get merged) and in the meantime this PR provides a solution to fix CloneProgram for projects using BTF.

**Review by safchain — APPROVED** [review]

**Comment by Gui774ume** [comment]
> > While this would work, I think it might better if we could scope an additional kernel BTF load/release around the `CloneProgram` call. That way you don't have to opt-in to a permanent memory increase to use `CloneProgram`.
> 
> Is it OK with you if I do it in another PR ? This will be a breaking change for the Datadog Agent (= will take more time to get merged) and in the meantime this PR provides a solution to fix `CloneProgram` for projects that use BTF.

Actually thinking about it, if you can provide it to `CloneProgram` then you're still keeping it in memory anyway, so what's the difference with asking the manager not to clean it up ? (assuming the use case of `CloneProgram` is usually to create new programs somewhat regularly VS statically on startup)

**Comment by Gui774ume** [comment]
Merging for now, we can revisit if need be.

**Pull request merged**
